### ISSUE TITLE
Since 0.5 update disconnected things need some sort of trigger to be reconnected

### ISSUE THREAD

**Issue by madb1lly** [WebThingsIO/thing-url-adapter#97]
Hello,

As mentioned in #iot, since the 0.5 update I've noticed that for any of my native WebThings which get disconnected, e.g. their battery runs out, a gateway reboot or scan for new Things is needed before the disconnected WebThing will reconnect.

For example:

- Native webthing running on batteries
- Batteries run out of energy
- Thing becomes disconnected
- I replace the batteries

Thing should reconnect immediately, but since 0.5 it doesn't, instead:

- Reboot gateway, or scan for new things
- Then the Thing is reconnected

Nothing obvious in the logs as far as I can tell, at least not from the thing-url-adapter (Highlights and Macros were looking for these WebThings but couldn't find them).

Cheers 🙂

**Comment by mrstegeman** [comment]
Closing, since you're no longer seeing this behavior.
